AWS_ACCESS_KEY_ID = 'YOUR-AWS-ACCESS-KEY-ID'
AWS_SECRET_ACCESS_KEY = 'YOUR-AWS-SECRET-ACCESS-KEY'

REGION = 'your-region'

ELASTIC_IPS = {
    'i-aaaaaaaa': '1.2.3.4',
    'i-bbbbbbbb': '5.6.7.8',
}

PROD_INSTANCE_TAG_KEY = 'env'
PROD_INSTANCE_TAG_VALUE = 'prod'